on: push
name: CI
jobs:
  build:
    name: "Build on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v0.10
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'cs'
        version: '7.8'
    - run: raco test main.rkt
