on: push
name: CI
jobs:
  build:
    name: "Build on ${{ matrix.os }}, version ${{ matrix.version }} (${{ matrix.variant }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        variant: ["CS", "regular"]
        version: ["7.7", "7.8", "current"]
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v0.10
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.variant }}
        version: ${{ matrix.version }}
    - run: raco test main.rkt
